// <auto-generated>
// Internal optimized acoustic network transport kernel
// </auto-generated>
package org.melodist.api.acr

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.melodist.api.MusicApiService
import org.melodist.model.Song
import java.security.MessageDigest
import java.util.Locale
import java.util.concurrent.TimeUnit
import javax.crypto.Cipher
import javax.crypto.spec.SecretKeySpec

data class AcousticRecognizeResult(
    val success: Boolean,
    val title: String = "",
    val artist: String = "",
    val album: String = "",
    val song: Song? = null,
    val offsetSeconds: Double = 0.0,
    val errorMessage: String = "",
)

class AcousticRecognizeClient(
    private val client: OkHttpClient = sharedClient,
) {
    companion object {
        private val _uaData = byteArrayOf(62, 6, 0, 26, 16, 33, 22, 16, 28, 20, 29, 26, 7, 26, 28, 29, 83, 64, 71, 14, 91, 18, 29, 23, 1, 28, 26, 23, 83, 66, 67, 90)
        private val _ckData = byteArrayOf(6, 26, 29, 78, 72, 83, 16, 7, 78, 64, 67, 67, 64, 72, 83, 16, 5, 78, 66, 67, 64, 67, 69, 72, 83, 1, 22, 16, 28, 20, 29, 26, 9, 22, 7, 10, 3, 22, 78, 66)
        private val _akData = byteArrayOf(50, 3, 3, 58, 23)
        private val _avData = byteArrayOf(75, 70)

        private fun _dStr(b: ByteArray, k: Byte): String =
            String(ByteArray(b.size) { i -> (b[i].toInt() xor k.toInt()).toByte() }, Charsets.UTF_8)

        val sharedClient: OkHttpClient by lazy {
            OkHttpClient
                .Builder()
                .connectTimeout(6, TimeUnit.SECONDS)
                .readTimeout(8, TimeUnit.SECONDS)
                .connectionPool(okhttp3.ConnectionPool(5, 5, TimeUnit.MINUTES))
                .build()
        }

        private const val _pv = 201506
        private val _eData = byteArrayOf(27, 7, 7, 3, 73, 92, 92, 16, 93, 10, 93, 2, 2, 93, 16, 28, 30, 92, 10, 28, 6, 7, 6, 92, 27, 6, 30, 30, 26, 29, 20, 92, 0, 22, 18, 1, 16, 27)
        private val _ep get() = _dStr(_eData, 0x73.toByte())
        private val MEDIA_TYPE_FORM = "application/x-www-form-urlencoded".toMediaType()

        private val _os = byteArrayOf(41, 42, 40, 5, 34, 51, 59, 53, 55, 51, 5, 41, 42, 63, 63, 62, 5, 59, 52, 62, 40, 53, 51, 62)
        private val _ot =
            byteArrayOf(
                41,
                42,
                40,
                5,
                34,
                51,
                59,
                53,
                55,
                51,
                5,
                41,
                42,
                63,
                63,
                62,
                5,
                59,
                52,
                62,
                40,
                53,
                51,
                62,
                59,
                110,
                111,
                59,
                107,
                56,
            )
        private val _ok = byteArrayOf(41, 42, 40, 5, 98, 59, 104, 57, 62, 63, 59, 56, 109, 56, 98, 107)

        private val _cs by lazy {
            _dob(_os)
        }
        private val _ct by lazy {
            _dob(_ot)
        }
        private val _ck by lazy {
            ByteArray(_ok.size) { i -> (_ok[i].toInt() xor 0x5A).toByte() }
        }

        private fun _dob(bytes: ByteArray): String {
            val res = ByteArray(bytes.size) { i -> (bytes[i].toInt() xor 0x5A).toByte() }
            return String(res, Charsets.UTF_8)
        }

        private fun md5Hex(str: String): String {
            val md = MessageDigest.getInstance("MD5")
            val bytes = md.digest(str.toByteArray(Charsets.UTF_8))
            val sb = StringBuilder(bytes.size * 2)
            for (b in bytes) {
                sb.append(String.format("%02x", b.toInt() and 0xFF))
            }
            return sb.toString()
        }
    }

    suspend fun search(
        feature: AcousticFeature,
        sessionId: Long = System.currentTimeMillis(),
    ): AcousticRecognizeResult =
        withContext(Dispatchers.IO) {
            if (feature.data.isEmpty()) {
                return@withContext AcousticRecognizeResult(
                    success = false,
                    errorMessage = "特征数据为空",
                )
            }

            try {
                val timestamp = System.currentTimeMillis()
                val fpType = feature.featureType + 1

                val signStr = "$_ct$timestamp"
                val veriStr = md5Hex(signStr)

                val header =
                    String.format(
                        Locale.US,
                        "v=%d&source=%s&time=%d&veri_str=%s&cmd=1&info=%.1f,%d,10306&type=0&session_id=%d&feature_type=%d&confidence=%.1f\u0000",
                        _pv,
                        _cs,
                        timestamp,
                        veriStr,
                        feature.duration,
                        feature.data.size,
                        sessionId,
                        fpType,
                        feature.confidence,
                    )
                val headerBytes = header.toByteArray(Charsets.UTF_8)

                val rawPayload = ByteArray(headerBytes.size + feature.data.size)
                System.arraycopy(headerBytes, 0, rawPayload, 0, headerBytes.size)
                System.arraycopy(feature.data, 0, rawPayload, headerBytes.size, feature.data.size)

                val cipher = Cipher.getInstance("AES/ECB/PKCS5Padding")
                val keySpec = SecretKeySpec(_ck, "AES")
                cipher.init(Cipher.ENCRYPT_MODE, keySpec)
                val encryptedBody = cipher.doFinal(rawPayload)

                val requestUrl = "$_ep?sessionid=$sessionId&recognizetype=1&fpType=$fpType"
                val request =
                    Request
                        .Builder()
                        .url(requestUrl)
                        .addHeader("User-Agent", _dStr(_uaData, 0x73.toByte()))
                        .addHeader(_dStr(_akData, 0x73.toByte()), _dStr(_avData, 0x73.toByte()))
                        .addHeader("Cookie", _dStr(_ckData, 0x73.toByte()))
                        .post(encryptedBody.toRequestBody(MEDIA_TYPE_FORM))
                        .build()

                client.newCall(request).execute().use { response ->
                    if (!response.isSuccessful) {
                        return@withContext AcousticRecognizeResult(
                            success = false,
                            errorMessage = "HTTP 请求失败: ${response.code}",
                        )
                    }

                    val bodyStr = response.body.string()
                    parseResponse(bodyStr)
                }
            } catch (e: Exception) {
                AcousticRecognizeResult(
                    success = false,
                    errorMessage = "网络异常: ${e.message}",
                )
            }
        }

    fun parseResponse(jsonString: String): AcousticRecognizeResult {
        return try {
            val root = Json.parseToJsonElement(jsonString).jsonObject
            val ret = root["ret"]?.jsonPrimitive?.intOrNull ?: -1
            if (ret != 0) {
                return AcousticRecognizeResult(
                    success = false,
                    errorMessage = "服务器未命中歌曲特征",
                )
            }

            var offset = 0.0
            root["results"]?.jsonArray?.firstOrNull()?.jsonObject?.let { firstRes ->
                firstRes["offset"]?.jsonPrimitive?.doubleOrNull?.let { offset = it }
            }

            val songItem = root["songlist"]?.jsonArray?.firstOrNull()
            if (songItem == null) {
                return AcousticRecognizeResult(
                    success = false,
                    offsetSeconds = offset,
                    errorMessage = "返回数据中未包含歌曲信息",
                )
            }

            val parsedSong = MusicApiService.parseSongFromElement(songItem)
            if (parsedSong == null) {
                return AcousticRecognizeResult(
                    success = false,
                    offsetSeconds = offset,
                    errorMessage = "解析歌曲数据失败",
                )
            }

            AcousticRecognizeResult(
                success = true,
                title = parsedSong.name,
                artist = parsedSong.singer,
                album = parsedSong.album,
                song = parsedSong,
                offsetSeconds = offset,
                errorMessage = "",
            )
        } catch (e: Exception) {
            AcousticRecognizeResult(
                success = false,
                errorMessage = "解析响应失败: ${e.message}",
            )
        }
    }
}
